# Generated by Django 2.1.2 on 2018-10-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Cuidades'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='nombre',
            new_name='Ncomuna',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='descripcion',
        ),
    ]
